[package]
name = "rust-merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
